# Generated by Django 3.2.3 on 2021-05-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_doctor',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_hospital',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_patient',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='staff',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
