# Generated by Django 3.2.3 on 2021-05-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_newuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
