# Generated by Django 3.2.3 on 2021-05-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_newuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
