# Generated by Django 3.2.3 on 2021-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_newuser_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='whichHosp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
