# Generated by Django 3.2.3 on 2021-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_newuser_whichhosp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='whichDoc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
