# Generated by Django 3.2.3 on 2021-06-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_newuser_whichdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='superuser',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
